name: Puppet_code_deployment

on:
  pull_request:
    types:
      - opened
      
jobs:
  call-workflow:
    uses: praveen-cheruku/puppet_code_manager/.github/workflows/puppet_code_manager.yml@main
    with:
      repo_name: ${{ github.repository }}
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit
